### ISSUE TITLE
LGTM

### ISSUE THREAD

**Issue by sweettea03** [tronprotocol/documentation-en#117]
LGTM

_Originally posted by @Benson0224 in https://github.com/tronprotocol/documentation-en/pull/97#pullrequestreview-781636242_

**Comment by sweettea03** [comment]
Identity indemnification theft pursuance slander-kashena Ragland aka owner

**Comment by CzDanial** [comment]
Yes i Owner . Why

**Comment by sweettea03** [comment]
Not of my accounts period. . @CzDanial
