### ISSUE TITLE
Cannot connect to official nodes for getBlockBalance

### ISSUE THREAD

**Issue by haorong4** [tronprotocol/documentation-en#189]
Hi, we failed to call the GetBlockBalance API from nodes 13.228.119.63 & 18.139.193.235 & 18.141.79.38 & 18.139.248.26. The error  indicate that there is a connection error. Could you help check why these 4 nodes are not working?
Here is the doc page for the API
https://developers.tron.network/reference/getblockbalance

**Comment by hitlxy** [comment]
I just tried it, and it works.  

```
curl --location --request POST 'http://13.228.119.63:8090/wallet/getblockbalance' \
--header 'Content-Type: application/json' \
--data-raw '{
  "hash": "000000000310479312fbd086fa20fa28bf7463feddc537c54ded14a96d6a9ed1",
  "number": 51398547,
  "visible": true
}'
```
