### ISSUE TITLE
Trx issues

### ISSUE THREAD

**Issue by Getrichisaac** [tronprotocol/documentation-en#199]
How to I trade or invest

**Comment by ferdinand026** [comment]
These are some guides: [Getting Started with Java-tron](https://tronprotocol.github.io/documentation-en/getting_started/getting_started_with_javatron/), [Reward for votes](https://tronprotocol.github.io/documentation-en/mechanism-algorithm/sr/#reward-for-voters), and [Stake on TRON](https://tronprotocol.github.io/documentation-en/mechanism-algorithm/resource/#staking-on-tron-network).

**Comment by Getrichisaac** [comment]
D
