### ISSUE TITLE
bscscan contracter stolen usdt from trust wallet 

### ISSUE THREAD

**Issue by goshe1234** [tronprotocol/documentation-en#204]
0xc9A4913ACF4Ad914e94f4eBecE24BA5c0b62FB6D 
this is wallet address on bscscan contracter stolen usdt from trust wallet all case was approved but my funds wasn't return even the block chains confirm me

**Comment by Stargazerr1** [comment]
I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by goshe1234** [comment]
how many pay uOn Sep 1, 2023 3:28 PM, Stargazerr1 ***@***.***> wrote:
I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110
