### ISSUE TITLE
Update Hardware Requirements

### ISSUE THREAD

**Issue by shadmau** [tronprotocol/documentation-en#212]
## Issue Description

The hardware requirements specified in the documentation seem to be outdated.

### Current Documentation States:

- Minimum Hardware Configuration: 8-core CPU, 16G memory, 1T SSD
- Recommended Configuration: 16-core CPU, 32G memory, 1.5T+ SSD
- Fullnode for Super Representative: 32-core CPU, 64G memory

### Actual Experience:

My node sync has consumed 1.9 TB and is still not fully synced. 

### Suggestion:

I suggest updating the documentation to reflect more accurate storage requirements based on recent data or growth trends. It would help operators to plan their infrastructure better and prevent them from encountering unexpected storage constraints.

**Comment by srbaeza-ai** [comment]
https://github.com/github/docs

**Comment by vivian1912** [comment]
@shadmau Thanks for your suggestion, and the document has been updated.
