### ISSUE TITLE
RECOVER YOUR SCAMMED FUNDS

### ISSUE THREAD

**Issue by bryanHills0** [tronprotocol/documentation-en#279]
HOW I WAS SCAMMED BY A FAKE CRYPTOCURRENCY INVESTMENT PLATFORM WHO SWINDLED $495,000 OUT OF MY RETIREMENT SAVINGS
“I invested with a Crypto broker without proper research to know what I was hoarding my hard-earned money into, only to find out it was a hoax and sham. I invested over $495,000 USD estimated to be 7.3 BTC. I was unable to make any withdrawals out of my initial deposits let alone the gains he claimed I have earned even after meeting the bogus fees and charges he is always requesting. Fortunately, I got to know about a RECOVER EXPERT that is well known and they are best tech skills in Bitcoin recovery programmers through research and positive reviews i saw about the good feedback from people that Has been into my kind of situations before on Google. After a couple of hours i consulted with them via TELEGRAM:https://t.me/RECOVERYEXPERT0  , via Email:RecoveryExpert01@consultant.com  within the next 24hours all my funds were recovered including my profits. I can’t thank these firm enough for making me not lose to these scammers. Thank you RECOVERY EXPERT. Consult them via:

email: RecoveryExpert01@consultant.com
WhatsApp: + 1 (908) 991 - 7132
Telegram;RECOVERY EXPERT https://t.me/RECOVERYEXPERT0

**Comment by Sokhanetaze80** [comment]
0x40B38765696e3d5d8d9d834D8AaD4bB6e418E489
