### ISSUE TITLE
Tron USDT: can Tether freeze your funds?

### ISSUE THREAD

**Issue by newnya** [tronprotocol/documentation-en#51]
Not really an issue, i would write this in the Discussion section, but there isn't one for this project.

So, the ERC-20 and Omni USDT tokens have a centralization issue: the Tether company has the control over your funds, like Paypal.

Can they freeze the TRC-20 USDT funds as well ?

**Comment by newnya** [comment]
Yes they can : https://cryptobriefing.com/tether-can-freeze-destroy-your-usdt/

**Comment by rejasire** [comment]
> Not really an issue, i would write this in the Discussion section, but there isn't one for this project.
> 
> So, the ERC-20 and Omni USDT tokens have a centralization issue: the Tether company has the control over your funds, like Paypal.
> 
> Can they freeze the TRC-20 USDT funds as well ?
