### ISSUE TITLE
Can't use fallback. Nothing happen! function() external payable {}

### ISSUE THREAD

**Issue by deniben** [tronprotocol/documentation-en#57]
```
pragma solidity >=0.5.1 <0.6.0;
contract HelloWorld {

    mapping(address => uint) public balance;
    uint public countOfInvestors = 0;
    mapping(address => uint) public time;
    event Invest(address investor, uint256 amount);
    
     function deposit() private {
        if (msg.value > 0) {
            if (balance[msg.sender] == 0) {
                countOfInvestors += 1;
            }
            balance[msg.sender] = msg.value;
            time[msg.sender] = now;
            emit Invest(msg.sender, msg.value);
        }
    }
   function() external payable {
       deposit();
   }
}
```
When i make deposit i have no new data on tronscan,  contract balance increased but not display any transaction
![image](https://user-images.githubusercontent.com/19304301/113033583-d97ffe80-9199-11eb-8281-de695f653f84.png)
How to make contract should what i need?
![image](https://user-images.githubusercontent.com/19304301/113033667-ef8dbf00-9199-11eb-906c-9ab857a8b696.png)
No one events but u sent few times
![image](https://user-images.githubusercontent.com/19304301/113033686-f61c3680-9199-11eb-9f99-c1ca04514dd1.png)
network shasta

**Comment by Benson0224** [comment]
here is one example of `payable` function, and works perfectly:

https://tronscan.org/#/contract/TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR/code
