### ISSUE TITLE
This issue is closed as no valid info. thanks.

### ISSUE THREAD

**Issue by bungfut** [tronprotocol/documentation-en#62]
[stripe_backup_code (1).txt](https://github.com/tronprotocol/documentation-en/files/6707235/stripe_backup_code.1.txt)
[NgonG]() This issue is closed as no valid info. thanks.

Please feel free to re-open it or create a new issue with detailed info, thanks.

_Originally posted by @Benson0224 in https://github.com/tronprotocol/documentation-en/issues/56#issuecomment-866584728_
RFC2617

**Comment by Benson0224** [comment]
Hi,
Can you please give more info on your issue? thanks.
