### ISSUE TITLE
100m$Smart Contract- Security 

### ISSUE THREAD

**Issue by thecontractlawcchanger** [tronprotocol/documentation-en#91]
Hi, as you’re aware and have my contract and it appears making some money while I sort out a situation. I didn’t complete the contract because I’ve been held under hostage with Evil users, @Justin here’s my proposal. I’ll reach out on telegram and we can execute the together. Should you except that I’ll provide an NDA and consider the potential pr or worse cases here that makes you a hero. And, I’ll provide all logs and data on how these guys did what they did.  

When I call you I’ll be in front a picture of a girl holding a key in the type of pay area street art I know you know of. 

*****Much love

JayWhite (Hat)
 “do the right thing, cause it’s the right thing to do”

**Comment by muhammadhaffizz** [comment]
Okey saya FAHAM ,,BULEH kah anda semak keputusan data beliau

**Comment by Kusmie00** [comment]
Hi
